import {
  LayoutDashboard,
  Users,
  GraduationCap,
  BookOpen,
  FileText,
  DollarSign,
  ShoppingCart,
  Package,
  Building2,
  Library,
  Calendar,
  MessageSquare,
  FileStack,
  Projector,
  Mic,
  HeadphonesIcon,
  Monitor,
  Shield,
  BarChart3,
  PieChart,
  FolderOpen,
  UserCheck,
  type LucideIcon,
} from "lucide-react";

export interface ModuleInfo {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  color: string;
  features: string[];
  subPages: { label: string; href: string }[];
  status: "em-breve" | "desenvolvimento" | "planejado";
}

export const modules: Record<string, ModuleInfo> = {
  dashboard: {
    slug: "dashboard",
    name: "Dashboard",
    description: "Visão executiva com indicadores, KPIs e métricas institucionais em tempo real.",
    icon: LayoutDashboard,
    color: "text-blue-600 bg-blue-50 dark:bg-blue-950/50",
    features: [
      "KPIs institucionais",
      "Gráficos interativos",
      "Comparativo entre unidades",
      "Alertas inteligentes",
      "Metas institucionais",
    ],
    subPages: [],
    status: "desenvolvimento",
  },
  alunos: {
    slug: "alunos",
    name: "Alunos",
    description: "Gestão completa do corpo discente, incluindo matrículas, histórico acadêmico e documentos.",
    icon: Users,
    color: "text-indigo-600 bg-indigo-50 dark:bg-indigo-950/50",
    features: [
      "Cadastro de alunos",
      "Matrículas e rematrículas",
      "Histórico escolar",
      "Transferências",
      "Emissão de documentos",
      "Frequência e notas",
    ],
    subPages: [
      { label: "Lista de Alunos", href: "/alunos" },
      { label: "Adicionar Aluno", href: "/alunos/novo" },
      { label: "Matrículas", href: "/alunos/matriculas" },
      { label: "Histórico", href: "/alunos/historico" },
    ],
    status: "desenvolvimento",
  },
  cursos: {
    slug: "cursos",
    name: "Cursos",
    description: "Gerenciamento de cursos técnicos, disciplinas, matrizes curriculares e certificações.",
    icon: GraduationCap,
    color: "text-emerald-600 bg-emerald-50 dark:bg-emerald-950/50",
    features: [
      "Cadastro de cursos",
      "Matrizes curriculares",
      "Disciplinas e ementas",
      "Certificados e diplomas",
      "Grade horária",
    ],
    subPages: [
      { label: "Lista de Cursos", href: "/cursos" },
      { label: "Novo Curso", href: "/cursos/novo" },
      { label: "Disciplinas", href: "/cursos/disciplinas" },
    ],
    status: "desenvolvimento",
  },
  turmas: {
    slug: "turmas",
    name: "Turmas",
    description: "Organização de turmas, alocação de professores, calendário e diário eletrônico.",
    icon: BookOpen,
    color: "text-violet-600 bg-violet-50 dark:bg-violet-950/50",
    features: [
      "Cadastro de turmas",
      "Alocação de professores",
      "Calendário acadêmico",
      "Diário eletrônico",
      "Acompanhamento pedagógico",
    ],
    subPages: [
      { label: "Lista de Turmas", href: "/turmas" },
      { label: "Calendário", href: "/turmas/calendario" },
    ],
    status: "desenvolvimento",
  },
  secretaria: {
    slug: "secretaria",
    name: "Secretaria Acadêmica",
    description: "Protocolos, declarações, certidões e emissão automática de documentos acadêmicos.",
    icon: FileText,
    color: "text-amber-600 bg-amber-50 dark:bg-amber-950/50",
    features: [
      "Protocolo digital",
      "Declarações e certidões",
      "Históricos escolares",
      "Assinatura digital",
      "Automação de documentos",
    ],
    subPages: [
      { label: "Protocolos", href: "/secretaria/protocolos" },
      { label: "Declarações", href: "/secretaria/declaracoes" },
      { label: "Certidões", href: "/secretaria/certidoes" },
    ],
    status: "desenvolvimento",
  },
  rh: {
    slug: "rh",
    name: "Recursos Humanos",
    description: "Gestão de servidores, professores, contratos, férias, licenças e treinamentos.",
    icon: UserCheck,
    color: "text-cyan-600 bg-cyan-50 dark:bg-cyan-950/50",
    features: [
      "Cadastro de servidores",
      "Professores e contratos",
      "Controle de férias e licenças",
      "Escalas de trabalho",
      "Treinamentos e avaliações",
    ],
    subPages: [
      { label: "Servidores", href: "/rh/servidores" },
      { label: "Professores", href: "/rh/professores" },
      { label: "Contratos", href: "/rh/contratos" },
      { label: "Férias", href: "/rh/ferias" },
    ],
    status: "desenvolvimento",
  },
  financeiro: {
    slug: "financeiro",
    name: "Financeiro",
    description: "Controle de receitas, despesas, empenhos, contratos e fluxo de caixa.",
    icon: DollarSign,
    color: "text-green-600 bg-green-50 dark:bg-green-950/50",
    features: [
      "Dashboard financeiro",
      "Receitas e despesas",
      "Empenhos e contratos",
      "Fluxo de caixa",
      "Centros de custo",
      "Prestação de contas",
    ],
    subPages: [
      { label: "Dashboard", href: "/financeiro" },
      { label: "Receitas", href: "/financeiro/receitas" },
      { label: "Despesas", href: "/financeiro/despesas" },
      { label: "Fluxo de Caixa", href: "/financeiro/fluxo" },
    ],
    status: "planejado",
  },
  compras: {
    slug: "compras",
    name: "Compras e Licitações",
    description: "Solicitações de compra, cotações, licitações, contratos e recebimentos.",
    icon: ShoppingCart,
    color: "text-orange-600 bg-orange-50 dark:bg-orange-950/50",
    features: [
      "Solicitações de compra",
      "Cotações e orçamentos",
      "Licitações",
      "Contratos",
      "Recebimento de materiais",
    ],
    subPages: [
      { label: "Solicitações", href: "/compras/solicitacoes" },
      { label: "Cotações", href: "/compras/cotacoes" },
      { label: "Licitações", href: "/compras/licitacoes" },
    ],
    status: "desenvolvimento",
  },
  almoxarifado: {
    slug: "almoxarifado",
    name: "Almoxarifado",
    description: "Gestão de estoque, entradas e saídas, inventário e transferências entre unidades.",
    icon: Package,
    color: "text-yellow-600 bg-yellow-50 dark:bg-yellow-950/50",
    features: [
      "Controle de estoque",
      "Entradas e saídas",
      "Inventário físico",
      "Estoque mínimo",
      "Transferências entre unidades",
      "Código de barras e QR Code",
    ],
    subPages: [
      { label: "Entradas", href: "/almoxarifado/entradas" },
      { label: "Saídas", href: "/almoxarifado/saidas" },
      { label: "Inventário", href: "/almoxarifado/inventario" },
    ],
    status: "desenvolvimento",
  },
  patrimonio: {
    slug: "patrimonio",
    name: "Patrimônio",
    description: "Tombamento, movimentações, manutenção, depreciação e baixa patrimonial.",
    icon: Building2,
    color: "text-slate-600 bg-slate-50 dark:bg-slate-950/50",
    features: [
      "Tombamento de bens",
      "Movimentações",
      "Controle de manutenção",
      "Depreciação",
      "Baixa patrimonial",
      "Inventário físico",
    ],
    subPages: [
      { label: "Bens Tombados", href: "/patrimonio/bens" },
      { label: "Movimentações", href: "/patrimonio/movimentacoes" },
      { label: "Manutenção", href: "/patrimonio/manutencao" },
    ],
    status: "desenvolvimento",
  },
  biblioteca: {
    slug: "biblioteca",
    name: "Biblioteca",
    description: "Acervo bibliográfico, empréstimos, renovações, reservas e multas.",
    icon: Library,
    color: "text-rose-600 bg-rose-50 dark:bg-rose-950/50",
    features: [
      "Cadastro de acervo",
      "Empréstimos e devoluções",
      "Renovações online",
      "Reservas",
      "Controle de multas",
      "QR Code para obras",
    ],
    subPages: [
      { label: "Acervo", href: "/biblioteca/acervo" },
      { label: "Empréstimos", href: "/biblioteca/emprestimos" },
      { label: "Reservas", href: "/biblioteca/reservas" },
    ],
    status: "desenvolvimento",
  },
  agenda: {
    slug: "agenda",
    name: "Agenda Institucional",
    description: "Eventos, reuniões, reservas de salas e laboratórios com calendário compartilhado.",
    icon: Calendar,
    color: "text-pink-600 bg-pink-50 dark:bg-pink-950/50",
    features: [
      "Eventos institucionais",
      "Reuniões agendadas",
      "Reserva de salas",
      "Reserva de laboratórios",
      "Calendário compartilhado",
    ],
    subPages: [
      { label: "Eventos", href: "/agenda/eventos" },
      { label: "Salas", href: "/agenda/salas" },
      { label: "Laboratórios", href: "/agenda/laboratorios" },
    ],
    status: "desenvolvimento",
  },
  ti: {
    slug: "ti",
    name: "Tecnologia da Informação",
    description: "Chamados técnicos, inventário de equipamentos, licenças de software e suporte.",
    icon: Monitor,
    color: "text-gray-600 bg-gray-50 dark:bg-gray-950/50",
    features: [
      "Abertura de chamados",
      "Inventário de equipamentos",
      "Licenças de software",
      "Controle de garantias",
      "Base de conhecimento",
    ],
    subPages: [
      { label: "Chamados", href: "/ti/chamados" },
      { label: "Equipamentos", href: "/ti/equipamentos" },
      { label: "Licenças", href: "/ti/licencas" },
    ],
    status: "planejado",
  },
  ouvidoria: {
    slug: "ouvidoria",
    name: "Ouvidoria",
    description: "Canal de comunicação com reclamações, sugestões, elogios, denúncias e relatórios.",
    icon: Mic,
    color: "text-purple-600 bg-purple-50 dark:bg-purple-950/50",
    features: [
      "Registro de manifestações",
      "Reclamações e denúncias",
      "Sugestões e elogios",
      "Acompanhamento de protocolos",
      "Relatórios gerenciais",
      "Anonimato garantido",
    ],
    subPages: [
      { label: "Reclamações", href: "/ouvidoria/reclamacoes" },
      { label: "Sugestões", href: "/ouvidoria/sugestoes" },
      { label: "Relatórios", href: "/ouvidoria/relatorios" },
    ],
    status: "desenvolvimento",
  },
  comunicacao: {
    slug: "comunicacao",
    name: "Comunicação",
    description: "Avisos institucionais, murais digitais, notificações por email/SMS/push.",
    icon: MessageSquare,
    color: "text-sky-600 bg-sky-50 dark:bg-sky-950/50",
    features: [
      "Avisos e comunicados",
      "Murais digitais",
      "Notificações push",
      "Envio de emails",
      "Integração WhatsApp",
      "SMS institucional",
    ],
    subPages: [],
    status: "planejado",
  },
  protocolo: {
    slug: "protocolo",
    name: "Protocolo Digital",
    description: "Abertura de processos, tramitação, assinaturas digitais e fluxos de aprovação.",
    icon: FileStack,
    color: "text-teal-600 bg-teal-50 dark:bg-teal-950/50",
    features: [
      "Abertura de processos",
      "Tramitação digital",
      "Fluxos de aprovação",
      "Assinatura digital",
      "Histórico completo",
      "Acompanhamento em tempo real",
    ],
    subPages: [],
    status: "planejado",
  },
  projetos: {
    slug: "projetos",
    name: "Gestão de Projetos",
    description: "Planejamento, cronogramas, equipes, custos e indicadores de projetos institucionais.",
    icon: Projector,
    color: "text-fuchsia-600 bg-fuchsia-50 dark:bg-fuchsia-950/50",
    features: [
      "Cadastro de projetos",
      "Cronogramas e milestones",
      "Equipes e responsáveis",
      "Controle de custos",
      "Indicadores de desempenho",
    ],
    subPages: [],
    status: "desenvolvimento",
  },
  atendimento: {
    slug: "atendimento",
    name: "Atendimento",
    description: "Sistema de senhas, fila de espera, recepção e atendimento presencial/online.",
    icon: HeadphonesIcon,
    color: "text-red-600 bg-red-50 dark:bg-red-950/50",
    features: [
      "Distribuição de senhas",
      "Fila de atendimento",
      "Recepção",
      "Atendimento online",
      "Painel de chamadas",
      "SLA e satisfação",
    ],
    subPages: [],
    status: "planejado",
  },
  relatorios: {
    slug: "relatorios",
    name: "Relatórios",
    description: "Geração de relatórios em PDF, Excel, CSV com agendamento e dashboards personalizados.",
    icon: BarChart3,
    color: "text-blue-600 bg-blue-50 dark:bg-blue-950/50",
    features: [
      "Relatórios acadêmicos",
      "Relatórios financeiros",
      "Exportação PDF/Excel/CSV",
      "Agendamento de relatórios",
      "Dashboards personalizados",
      "Relatórios LGPD",
    ],
    subPages: [],
    status: "desenvolvimento",
  },
  bi: {
    slug: "bi",
    name: "Business Intelligence",
    description: "Indicadores estratégicos, metas institucionais, analytics e comparativos entre unidades.",
    icon: PieChart,
    color: "text-indigo-600 bg-indigo-50 dark:bg-indigo-950/50",
    features: [
      "Indicadores estratégicos",
      "Metas institucionais",
      "Performance por unidade",
      "Analytics acadêmico",
      "Comparativo histórico",
      "Exportação de dados",
    ],
    subPages: [],
    status: "desenvolvimento",
  },
  ged: {
    slug: "ged",
    name: "GED - Gestão Eletrônica",
    description: "Upload, OCR, versionamento, assinatura digital e pesquisa avançada de documentos.",
    icon: FolderOpen,
    color: "text-amber-600 bg-amber-50 dark:bg-amber-950/50",
    features: [
      "Upload de documentos",
      "Reconhecimento OCR",
      "Versionamento",
      "Assinatura digital",
      "Pesquisa avançada",
      "Categorização automática",
    ],
    subPages: [],
    status: "planejado",
  },
  auditoria: {
    slug: "auditoria",
    name: "Auditoria",
    description: "Logs completos, histórico de alterações, rastreamento de IP e controle de sessões.",
    icon: Shield,
    color: "text-zinc-600 bg-zinc-50 dark:bg-zinc-950/50",
    features: [
      "Logs de auditoria",
      "Histórico de alterações",
      "Rastreamento de IP",
      "Controle de sessões",
      "Relatórios de auditoria",
      "Conformidade LGPD",
    ],
    subPages: [],
    status: "desenvolvimento",
  },
  configuracoes: {
    slug: "configuracoes",
    name: "Configurações",
    description: "Configurações gerais do sistema, unidades, perfis de acesso e preferências.",
    icon: FileText,
    color: "text-neutral-600 bg-neutral-50 dark:bg-neutral-950/50",
    features: [
      "Configurações da instituição",
      "Gestão de unidades",
      "Perfis e permissões",
      "Preferências do sistema",
      "Integrações",
      "Backup e segurança",
    ],
    subPages: [],
    status: "desenvolvimento",
  },
};

export function getModuleInfo(slug: string): ModuleInfo | undefined {
  return modules[slug];
}

