import {
  LayoutDashboard,
  Users,
  GraduationCap,
  BookOpen,
  FileText,
  DollarSign,
  ShoppingCart,
  Package,
  Building2,
  Library,
  Calendar,
  MessageSquare,
  FileStack,
  Projector,
  Mic,
  HeadphonesIcon,
  Monitor,
  Shield,
  BarChart3,
  PieChart,
  UserCheck,
  BookMarked,
  ShieldCheck,
  KeyRound,
} from "lucide-react";
import type { NavEntry } from "@/types/navigation";

export const navigationItems: NavEntry[] = [
  {
    type: "section",
    label: "Principal",
  },
  {
    type: "item",
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    type: "section",
    label: "Acadêmico",
  },
  {
    type: "item",
    label: "Alunos",
    href: "/alunos",
    icon: Users,
    badge: "1.2k",
    subItems: [
      { label: "Lista", href: "/alunos", icon: Users },
      { label: "Adicionar", href: "/alunos/novo", icon: Users },
      { label: "Matrículas", href: "/alunos/matriculas", icon: Users },
      { label: "Histórico", href: "/alunos/historico", icon: BookMarked },
    ],
  },
  {
    type: "item",
    label: "Cursos",
    href: "/cursos",
    icon: GraduationCap,
    subItems: [
      { label: "Lista", href: "/cursos", icon: GraduationCap },
      { label: "Novo Curso", href: "/cursos/novo", icon: GraduationCap },
      { label: "Disciplinas", href: "/cursos/disciplinas", icon: BookOpen },
    ],
  },
  {
    type: "item",
    label: "Turmas",
    href: "/turmas",
    icon: BookOpen,
    subItems: [
      { label: "Lista", href: "/turmas", icon: BookOpen },
      { label: "Calendário", href: "/turmas/calendario", icon: Calendar },
    ],
  },
  {
    type: "item",
    label: "Secretaria",
    href: "/secretaria",
    icon: FileText,
    subItems: [
      { label: "Protocolos", href: "/secretaria/protocolos", icon: FileStack },
      { label: "Declarações", href: "/secretaria/declaracoes", icon: FileText },
      { label: "Certidões", href: "/secretaria/certidoes", icon: FileText },
    ],
  },
  {
    type: "section",
    label: "Gestão",
  },
  {
    type: "item",
    label: "Recursos Humanos",
    href: "/rh",
    icon: UserCheck,
    subItems: [
      { label: "Servidores", href: "/rh/servidores", icon: Users },
      { label: "Professores", href: "/rh/professores", icon: UserCheck },
      { label: "Contratos", href: "/rh/contratos", icon: FileText },
      { label: "Férias", href: "/rh/ferias", icon: Calendar },
    ],
  },
  {
    type: "item",
    label: "Financeiro",
    href: "/financeiro",
    icon: DollarSign,
    subItems: [
      { label: "Dashboard", href: "/financeiro", icon: DollarSign },
      { label: "Receitas", href: "/financeiro/receitas", icon: DollarSign },
      { label: "Despesas", href: "/financeiro/despesas", icon: DollarSign },
      { label: "Fluxo de Caixa", href: "/financeiro/fluxo", icon: BarChart3 },
    ],
  },
  {
    type: "item",
    label: "Compras",
    href: "/compras",
    icon: ShoppingCart,
    subItems: [
      { label: "Solicitações", href: "/compras/solicitacoes", icon: ShoppingCart },
      { label: "Cotações", href: "/compras/cotacoes", icon: ShoppingCart },
      { label: "Licitações", href: "/compras/licitacoes", icon: FileText },
    ],
  },
  {
    type: "item",
    label: "Almoxarifado",
    href: "/almoxarifado",
    icon: Package,
    subItems: [
      { label: "Entradas", href: "/almoxarifado/entradas", icon: Package },
      { label: "Saídas", href: "/almoxarifado/saidas", icon: Package },
      { label: "Inventário", href: "/almoxarifado/inventario", icon: BarChart3 },
    ],
  },
  {
    type: "item",
    label: "Patrimônio",
    href: "/patrimonio",
    icon: Building2,
    subItems: [
      { label: "Bens", href: "/patrimonio/bens", icon: Building2 },
      { label: "Movimentações", href: "/patrimonio/movimentacoes", icon: Building2 },
      { label: "Manutenção", href: "/patrimonio/manutencao", icon: Monitor },
    ],
  },
  {
    type: "section",
    label: "Serviços",
  },
  {
    type: "item",
    label: "Biblioteca",
    href: "/biblioteca",
    icon: Library,
    subItems: [
      { label: "Acervo", href: "/biblioteca/acervo", icon: Library },
      { label: "Empréstimos", href: "/biblioteca/emprestimos", icon: BookOpen },
      { label: "Reservas", href: "/biblioteca/reservas", icon: Calendar },
    ],
  },
  {
    type: "item",
    label: "Agenda",
    href: "/agenda",
    icon: Calendar,
    subItems: [
      { label: "Eventos", href: "/agenda/eventos", icon: Calendar },
      { label: "Salas", href: "/agenda/salas", icon: Building2 },
      { label: "Laboratórios", href: "/agenda/laboratorios", icon: Monitor },
    ],
  },
  {
    type: "item",
    label: "TI",
    href: "/ti",
    icon: Monitor,
    subItems: [
      { label: "Chamados", href: "/ti/chamados", icon: HeadphonesIcon },
      { label: "Equipamentos", href: "/ti/equipamentos", icon: Monitor },
      { label: "Licenças", href: "/ti/licencas", icon: FileText },
    ],
  },
  {
    type: "item",
    label: "Ouvidoria",
    href: "/ouvidoria",
    icon: Mic,
    subItems: [
      { label: "Reclamações", href: "/ouvidoria/reclamacoes", icon: Mic },
      { label: "Sugestões", href: "/ouvidoria/sugestoes", icon: MessageSquare },
      { label: "Relatórios", href: "/ouvidoria/relatorios", icon: BarChart3 },
    ],
  },
  {
    type: "section",
    label: "Inteligência",
  },
  {
    type: "item",
    label: "Relatórios",
    href: "/relatorios",
    icon: BarChart3,
  },
  {
    type: "item",
    label: "BI",
    href: "/bi",
    icon: PieChart,
  },
  {
    type: "item",
    label: "Projetos",
    href: "/projetos",
    icon: Projector,
  },
  {
    type: "section",
    label: "Administração",
  },
  {
    type: "item",
    label: "Usuários",
    href: "/admin/usuarios",
    icon: Users,
    subItems: [
      { label: "Lista", href: "/admin/usuarios", icon: Users },
      { label: "Novo", href: "/admin/usuarios/novo", icon: Users },
    ],
  },
  {
    type: "item",
    label: "Perfis",
    href: "/admin/perfis",
    icon: ShieldCheck,
  },
  {
    type: "item",
    label: "Permissões",
    href: "/admin/permissoes",
    icon: KeyRound,
  },
  {
    type: "section",
    label: "Sistema",
  },
  {
    type: "item",
    label: "Auditoria",
    href: "/auditoria",
    icon: Shield,
  },
  {
    type: "item",
    label: "Configurações",
    href: "/configuracoes",
    icon: FileText,
  },
];
